### ISSUE TITLE
Is this still being developed on GitHub?

### ISSUE THREAD

**Issue by Japh** [WPGov/telegram-bot#1]
I notice the version on GitHub is quite old compared with the version on the WordPress plugin directory. Does that mean development is now only happening on the plugin directory SVN repository?

@milesimarco I would like to log issues and submit pull requests, if there is a GitHub repository somewhere still?

Thanks!

**Comment by milesimarco** [comment]
Hi,
files have been updated. I don't update them frequently because i used SVN for this project.

Thank you for your interest!

**Comment by sabarayane** [comment]
Hi,
I install your wp addon , but It seems need more sample data for help , 
1) commands and menu options not set to gether , or how to set a command to a menu key ?
2) in command description , text is goling to telegram app, but picture not transfer ! how can fix this problem
thanks.

**Comment by milesimarco** [comment]
Hi,
what do you mean for menu options? Keyboard? Keyboard commands must match your commands. You can define commands in your admin dashboard and you can define multiple commands at once (eg. by adding in the title: "/help,help").

Check this thread for the photo bug
https://wordpress.org/support/topic/image-in-commands
